DROP TABLE PROPERTY;
DROP TABLE GRADE;
DROP TABLE CIRCUIT;
DROP TABLE SUITE;
DROP TABLE PROBLEM;

CREATE TABLE PROBLEM (
	PROBLEM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME varchar(255) NOT NULL,
	USE_MEMORY INTEGER NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT PROBLEM_PK PRIMARY KEY (PROBLEM_ID),
	CONSTRAINT PROBLEM_UK UNIQUE (NAME)
);

CREATE TABLE SUITE (
	SUITE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PROBLEM_ID INT NOT NULL,
	OBJECT CLOB NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT SUITE_PK PRIMARY KEY (SUITE_ID),
	CONSTRAINT SUITE_PROBLEM_FK FOREIGN KEY (PROBLEM_ID) REFERENCES PROBLEM (PROBLEM_ID)
);

CREATE TABLE CIRCUIT (
	CIRCUIT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SUITE_ID INT NOT NULL,
	POSITION INT NOT NULL,
	OBJECT CLOB NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT CIRCUIT_PK PRIMARY KEY (CIRCUIT_ID),
	CONSTRAINT CIRCUIT_SUITE_FK FOREIGN KEY (SUITE_ID) REFERENCES SUITE (SUITE_ID)
);

CREATE TABLE PROPERTY (
	PROPERTY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	VAL VARCHAR(255),
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT PROPERTY_PK PRIMARY KEY (PROPERTY_ID),
	CONSTRAINT PROPERTY_UK UNIQUE (NAME)
);

insert into problem (name, use_memory , created) values ('CHAR_TYPE', 1, current_timestamp);
insert into problem (name, use_memory , created) values ('SPORTING_BET', 0, current_timestamp);

insert into property (name, val , created) values ('LOCK', null, current_timestamp);
