package org.genetics.camel.configuration;

public interface Constants {

    public String HEADER_POSITION = "POSITION";

    public String HEADER_PROBLEM_NAME = "PROBLEM_NAME";

    public String HEADER_POPULATION_GENERATION = "POPULATION_GENERATION";

    public String HEADER_GENERATOR_METHOD = "GENERATOR_METHOD";

    public String GENERATOR_METHOD_RANDOM = "RANDOM";
    public String GENERATOR_METHOD_MIX_EXISTING = "MIX_EXISTING";
    public String GENERATOR_METHOD_ENRICH_EXISTING = "ENRICH_EXISTING";
    public String GENERATOR_METHOD_MIGRATE_RANDOM_FROM_DATABASE = "MIGRATE_RANDOM_FROM_DATABASE";

}
